const images = {
  DXP01: require("styles/images/aboutMe/DuongXuanPhi01.png"),
  DXP02: require("styles/images/aboutMe/DuongXuanPhi02.png"),
  DXP03: require("styles/images/aboutMe/DuongXuanPhi03.png"),
  Text_DXP01: require("styles/images/aboutMe/TextDXP.png"),
  xedap: require("./xe đạp 1.svg"),
  duongxuanphi_text: require("./duongxuanphi_text.svg"),
  DXP_trenbien01: require("./DXPtrenbien01.png"),
  DXP_trenui01: require("./DXPtrenui01.png"),
  DXP_trenui02: require("./DXPtrenui02.png"),
  DXP_xedap01: require("./DXPxedap01.png"),
  Utopia_la: require("./utopia-la.png"),
  khoa_01: require("./khoa01_DXP.png"),
  Utopia_01: require("styles/images/aboutMe/utopia-01.png"),
  Utopia_02: require("styles/images/aboutMe/utopia2_02.svg"),
  Utopia_03: require("styles/images/aboutMe/utopia-03.png"),
  Utopia_04: require("styles/images/aboutMe/utopia-04.png"),
  Utopia_05: require("styles/images/aboutMe/utopia-05.png"),
  Utopia_06: require("styles/images/aboutMe/utopia-06.png"),
  Utopia_07: require("styles/images/aboutMe/utopia-07.png"),
  Uto_01: require("styles/images/aboutMe/uto-01.png"),
  Uto_02: require("styles/images/aboutMe/uto-02.png"),
  Utop_03: require("styles/images/aboutMe/uto-03.png"),
  Uto_04: require("styles/images/aboutMe/uto-04.png"),
  Uto_05: require("styles/images/aboutMe/uto-05.png"),
  jgooooo_01: require("styles/images/aboutMe/jgooooo-01.png"),
  jgooooo_02: require("styles/images/aboutMe/jgooooo-02.png"),
  jgooooo_03: require("styles/images/aboutMe/jgooooo-03.png"),
  utopia_view: require("styles/images/aboutMe/utopia_view.png"),
};
export default images;
