const images = {
    DXP_01: require("styles/images/aboutMobi/DXP_01.png"),
    DXP_02: require("styles/images/aboutMobi/DXP_02.png"),
    DXP_03: require("styles/images/aboutMobi/DXP_03.png"),
    text: require("./text.svg"),
    xedap: require("./xedap.svg"),
    utopia_01: require("styles/images/aboutMobi/utopia_01.svg"),
    text_2016: require("styles/images/aboutMobi/text_2016.svg"),
    text_2020: require("styles/images/aboutMobi/text_2020.svg"),
    text_2021: require("styles/images/aboutMobi/text_2021.svg"),
    duongxuanphi_text: require("styles/images/aboutMobi/duongxuanphi_text.svg"),
    uto_01: require("styles/images/aboutMobi/uto_01.png"),
    uto_02: require("styles/images/aboutMobi/uto_02.png"),
    uto_03: require("styles/images/aboutMobi/uto_03.png"),
    jgooooo_01: require("styles/images/aboutMobi/jgooooo_01.png"),
    jgooooo_02: require("styles/images/aboutMobi/jgooooo_02.png"),
    dxp_05: require("./dxp_05.png"),
    dxp_06: require("./dxp_06.png"),
    dxp_07: require("./dxp_07.png"),
    dxp_08: require("./dxp_08.png"),
    uto_1: require("./uto_1.png"),
    uto_2: require("./uto_2.png"),
    uto_3: require("./uto_3.png"),
    uto_4: require("./uto_4.png"),
    uto_5: require("./uto_5.png"),
    uto_6: require("./uto_6.png"),
    utotech: require("./utotech.png"),
}
export default images